// <auto-generated />
using System;
using GestionProyectos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionProyectos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803001512_AddOutboxMessages")]
    partial class AddOutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionProyectos.Domain.Entities.Column", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Order")
                        .HasDatabaseName("ix_columns_project_id_order");

                    b.ToTable("columns", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000001"),
                            IsDeleted = false,
                            Name = "Por hacer",
                            Order = 0,
                            ProjectId = new Guid("d0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000002"),
                            IsDeleted = false,
                            Name = "En progreso",
                            Order = 1,
                            ProjectId = new Guid("d0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000003"),
                            IsDeleted = false,
                            Name = "Hecho",
                            Order = 2,
                            ProjectId = new Guid("d0000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "ix_projects_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_projects_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_projects_name_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "Name" }, "ix_projects_name_unique")
                        .IsUnique()
                        .HasFilter("NOT is_deleted");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            Description = "Proyecto de ejemplo precargado por la migracion semilla para probar el tablero, el tiempo real y los reportes sin crear datos manualmente.",
                            EndDate = new DateOnly(2026, 12, 31),
                            IsDeleted = false,
                            Name = "Proyecto Demo",
                            StartDate = new DateOnly(2026, 7, 1),
                            Status = 1
                        });
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("column_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ColumnId", "Order")
                        .HasDatabaseName("ix_tasks_column_id_order");

                    b.ToTable("tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000001"),
                            AssigneeId = new Guid("6f9b1c2e-1a2b-4c3d-8e4f-000000000001"),
                            ColumnId = new Guid("d1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bocetos iniciales de las pantallas principales del tablero.",
                            IsDeleted = false,
                            Order = "m",
                            Priority = 2,
                            Title = "Diseñar wireframes"
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000002"),
                            AssigneeId = new Guid("6f9b1c2e-1a2b-4c3d-8e4f-000000000002"),
                            ColumnId = new Guid("d1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Listar las funcionalidades minimas para el primer release.",
                            IsDeleted = false,
                            Order = "t",
                            Priority = 1,
                            Title = "Definir alcance del MVP"
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000003"),
                            AssigneeId = new Guid("6f9b1c2e-1a2b-4c3d-8e4f-000000000001"),
                            ColumnId = new Guid("d1000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JWT, guardia de ruta e interceptor con manejo de 401.",
                            IsDeleted = false,
                            Order = "m",
                            Priority = 3,
                            Title = "Implementar login"
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000004"),
                            ColumnId = new Guid("d1000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Paginacion y filtro por nombre resuelto en el servidor.",
                            IsDeleted = false,
                            Order = "t",
                            Priority = 2,
                            Title = "CRUD de proyectos"
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000005"),
                            AssigneeId = new Guid("6f9b1c2e-1a2b-4c3d-8e4f-000000000002"),
                            ColumnId = new Guid("d1000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arquitectura hexagonal, Angular con Sakai y docker-compose.",
                            IsDeleted = false,
                            Order = "m",
                            Priority = 0,
                            Title = "Cimientos del proyecto"
                        });
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f9b1c2e-1a2b-4c3d-8e4f-000000000001"),
                            Email = "luis.renteria@ideasgroup.test",
                            Name = "Luis Rentería",
                            PasswordHash = "$2a$11$YJ0PQ4j9uGPeu.c0KarD3.nWP8.o7KjhuJ8P/W6JxT4vXAKvumGhu"
                        },
                        new
                        {
                            Id = new Guid("6f9b1c2e-1a2b-4c3d-8e4f-000000000002"),
                            Email = "evaluador@ideasgroup.test",
                            Name = "Evaluador",
                            PasswordHash = "$2a$11$YJ0PQ4j9uGPeu.c0KarD3.nWP8.o7KjhuJ8P/W6JxT4vXAKvumGhu"
                        });
                });

            modelBuilder.Entity("GestionProyectos.Infrastructure.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExcludeConnectionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exclude_connection_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_pending");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("GestionProyectos.Infrastructure.Persistence.Entities.RevokedToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("jti");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.HasKey("Jti");

                    b.ToTable("revoked_tokens", (string)null);
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entities.Column", b =>
                {
                    b.HasOne("GestionProyectos.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionProyectos.Domain.Entities.TaskEntity", b =>
                {
                    b.HasOne("GestionProyectos.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionProyectos.Domain.Entities.Column", null)
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
